# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(verbose_name='音乐ID')),
                ('music_name', models.CharField(max_length=255, verbose_name='音乐名')),
                ('singer', models.CharField(max_length=255, verbose_name='歌手')),
                ('lrc', models.TextField(verbose_name='歌词')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
        ),
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integ', models.CharField(max_length=255, verbose_name='押韵组合')),
                ('count', models.IntegerField(default=1, verbose_name='韵脚数')),
                ('num', models.IntegerField(default=2, verbose_name='押韵字数')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='押韵词汇')),
                ('count', models.IntegerField(default=1, verbose_name='计数')),
                ('flag', models.CharField(max_length=255, verbose_name='词性')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否可用')),
                ('rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.Rhyme', verbose_name='押韵词汇')),
            ],
        ),
    ]
