# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrc',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='是否分析过'),
        ),
    ]
