# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='项目名')),
                ('abstract', models.TextField(verbose_name='简介')),
                ('image', models.ImageField(upload_to='/pic', verbose_name='配图')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('url_mark', models.CharField(max_length=20, verbose_name='url标记')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_time', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
    ]
