# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='pic', verbose_name='配图'),
        ),
    ]
