# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpage', '0003_auto_20170626_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=None, verbose_name='内容'),
        ),
    ]
