# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='章节名')),
                ('is_alive', models.BooleanField(default=True, verbose_name='状态')),
                ('is_full', models.BooleanField(verbose_name='是否达到50')),
            ],
        ),
        migrations.CreateModel(
            name='Expand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explansion', models.TextField(verbose_name='解释')),
                ('is_alive', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='单词')),
                ('explansion', models.TextField(verbose_name='解释')),
                ('phonogram', models.CharField(max_length=255, verbose_name='音标')),
                ('is_alive', models.BooleanField(default=True, verbose_name='状态')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recite.Chapter', verbose_name='所属章节')),
            ],
        ),
        migrations.AddField(
            model_name='expand',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recite.Word', verbose_name='所属词汇'),
        ),
    ]
