# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['chapter']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chap',
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('chapter', 'word')]),
        ),
    ]
