# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recite', '0003_auto_20170824_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expand',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expand', to='recite.Word', verbose_name='所属词汇'),
        ),
    ]
