# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recite', '0004_auto_20170825_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='expand',
            name='provider',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='提供者的IP'),
        ),
    ]
