# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100, verbose_name='请求IP地址')),
                ('req_count', models.IntegerField(default=0, verbose_name='总请求次数')),
                ('limit_count', models.IntegerField(default=0, verbose_name='限制请求次数')),
                ('limit', models.CharField(choices=[('T', '限制'), ('F', '不限制')], default='F', max_length=10, verbose_name='限制访问')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourse', models.CharField(max_length=50, verbose_name='来源')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('port', models.CharField(blank=True, max_length=20, null=True, verbose_name='Port')),
                ('head', models.CharField(blank=True, max_length=10, null=True, verbose_name='Head')),
                ('status', models.CharField(choices=[('V', 'VALID'), ('I', 'INVALID')], max_length=10, verbose_name='状态')),
                ('type', models.CharField(choices=[('G', '高匿'), ('T', '透明'), ('O', '其他')], default='O', max_length=20, verbose_name='类型')),
                ('district', models.CharField(default='其他', max_length=50, verbose_name='地区')),
                ('Validated_time', models.IntegerField(blank=True, default=1, null=True, verbose_name='通过验证次数')),
                ('failed_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='连续验证失败次数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
