# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='insturction',
            new_name='instruction',
        ),
        migrations.AddField(
            model_name='tool',
            name='mark',
            field=models.CharField(default='#', max_length=20, verbose_name='URL标记'),
        ),
    ]
