# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20170616_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='tools/pic/', verbose_name='缩略图'),
        ),
    ]
