# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
